spring:
  datasource:
    #url: jdbc:postgresql://ingela.com:5434/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    #url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 123
    #password: Reme6502tva#
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: true
    #database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        security:
          oauth2=DEBUG: